title: Tyler Smith
logo: /assets/img/headshot_circle.png
description: Customer Engineer with over 8 years of experience offering outstanding 
support to users and teams of various levels. Exceptional skills and knowledge in 
Technical Support and subject matter expert on Windows Servers, 
Windows Desktops, Microsoft 365, Azure, and AWS. Established reputation as a sharp 
technology expert when working with customers to identify and deploy 
solutions.
show_downloads: false
theme: jekyll-theme-minimal